mural/panels/urls.py
from django.urls import path

from . import views

app_name="panels"

urlpatterns = [
    path('<slug:slug>/<article_type>/', views.PanelArticleView.as_view(), name='article_detail'),
    path('<slug:slug>/', views.PanelDetailView.as_view(), name='panel_detail'),
]

mural/pops/urls.py
from django.urls import path

from . import views

app_name="pops"

urlpatterns = [

    path('credits/ajax/<int:pk>/', views.CreditsDetailView.as_view(), 
        name='credits_ajax_detail'),

    path('today/ajax/<int:pk>/', views.TodayDetailView.as_view(), 
        name='today_ajax_detail'),

    path('video/ajax/<int:pk>/', views.VideoDetailView.as_view(), 
        name='video_ajax_detail'),

    path('visit/ajax/<int:pk>/', views.VisitDetailView.as_view(), 
        name='visit_ajax_detail'),

    path('voices/ajax/<int:pk>/', views.VoicesDetailView.as_view(), 
        name='voices_ajax_detail'),

    path('hotspot/ajax/<slug:slug>/', views.HotspotDetailView.as_view(), 
        name='hotspot_ajax_detail'),

    # first call is without slide_num
    path('images/ajax/<int:pk>/', views.ImagesDetailView.as_view(), 
        name='images_ajax_detail'),
    path('images/ajax/<int:pk>/<int:slide_num>/', views.ImagesDetailView.as_view(), 
        name='images_num_ajax_detail'),
    
    path('objects/ajax/<int:pk>/', views.ObjectsDetailView.as_view(), 
        name='objects_ajax_detail'),
    path('objects/ajax/<int:pk>/<int:slide_num>/', views.ObjectsDetailView.as_view(), 
        name='objects_num_ajax_detail'),

]

mural/panels/models.py
from django.db import models

# Create your models here.

class Panel(models.Model):
    slug = models.SlugField('short name', max_length=48, unique=True)
    panel_title = models.CharField(max_length=48)
    panel_blurb = models.TextField(blank=True, default='')
    foreground_title = models.CharField(max_length=128, blank=True, default='')
    ordinal = models.IntegerField('Panel number', default=99)

    # return list of panels
    def panel_list(self):
        return Panel.objects.all()

    # provide x for postion in main menu
    def main_x(self):
        return 3 + ((self.ordinal - 1)*339)

    # provide x for postion in main menu
    def mini_x(self):
        return 4 + ((self.ordinal - 1)*13)

    # next, prev slide, false if none
    def get_next(self):
        next_list = Panel.objects.filter(ordinal__gt=self.ordinal)
        if next_list:
            return next_list.first()
        return False

    # Special condition added to prevent going back to slide 0 which is the intro
    def get_prev(self):
        prev_list = Panel.objects.filter(ordinal__lt=self.ordinal).order_by('-ordinal')
        if prev_list:
            prev = prev_list.first()
            if prev.ordinal > 0:
                return prev_list.first()
        return False

    class Meta:
        ordering = ['ordinal']

    def __str__(self):
        return str(self.ordinal) + "-" + self.panel_title

class Article(models.Model):
    """docstring for Article"""
    ARTICLE_TYPE = (
        ('intro','Introduction'),
        ('fore','Foreground'),
        ('back','Background'),
    )
    panel = models.ForeignKey('panels.Panel', on_delete=models.CASCADE)
    article_type = models.CharField(max_length=12, default='intro', 
        choices=ARTICLE_TYPE)
    title = models.CharField(max_length=48, default='Title goes here')
    image_name = models.CharField(max_length=32, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['panel', '-article_type']

    def __str__(self):
        return str(self.panel.ordinal) + "-" + \
            self.panel.panel_title + "-" + self.article_type
        

mural/pops/models.py
from django.db import models

class Learnmore(models.Model):
    """docstring for Learnmore"""
    LEARMORE_TYPE = (
        ('images','Images'),
        ('objects','Objects'),
        ('credits','Credits'),
        ('today','Today'),
        ('video','Video Story'),
        ('voices','Voices'),
    )
    article = models.ForeignKey('panels.Article', on_delete=models.CASCADE)
    learnmore_type = models.CharField(max_length=12, default='today', 
        choices=LEARMORE_TYPE)
    # slug = models.SlugField('short name', max_length=48, unique=True)
    title = models.CharField(max_length=48)
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    def __str__(self):
        return "p" + str(self.article.panel.ordinal) + \
        "-" + self.article.article_type + "-" + self.learnmore_type
        

class Slide(models.Model):
    learnmore = models.ForeignKey('pops.Learnmore', on_delete=models.CASCADE)
    slide_num = models.IntegerField()
    title = models.CharField(max_length=48, blank=True, default='')
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    # next, prev slide, false if none
    def get_next(self):
        next_list = Slide.objects.filter(learnmore_id=self.learnmore_id, 
            slide_num__gt=self.slide_num)
        if next_list:
            return next_list.first()
        return False

    # Special condition added to prevent going back to slide 0 which is the intro
    def get_prev(self):
        prev_list = Slide.objects.filter(learnmore_id=self.learnmore_id, 
            slide_num__lt=self.slide_num).order_by('-slide_num')
        if prev_list:
            prev = prev_list.first()
            if prev.slide_num > 0:
                return prev_list.first()
        return False

    class Meta:
        ordering = ['slide_num']


    def __str__(self):
        return self.learnmore.title + str(self.slide_num)


class Voice(models.Model):
    learnmore = models.ForeignKey('pops.Learnmore', on_delete=models.CASCADE)
    part_num = models.IntegerField('Audio number')
    title = models.CharField(max_length=64, blank=True, default='')
    narrative = models.TextField('Transcription', blank=True, default='')
    # citation = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['part_num']

    def __str__(self):
        return self.learnmore.title + str(self.part_num)

class Visit(models.Model):
    """
    Visit is different from Learnmore because it is a child of Panel, not
    of Article
    """
    panel = models.ForeignKey('panels.Panel', on_delete=models.CASCADE)
    title = models.CharField(max_length=48)
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    def __str__(self):
        return "p" + str(self.panel.ordinal) + \
        "-" + self.panel.slug + "-visit"


class Hotspot(models.Model):
    """docstring for Visit"""
    panel = models.ForeignKey('panels.Panel', on_delete=models.CASCADE)
    slug = models.SlugField('short name', max_length=48, unique=True)
    title = models.CharField(max_length=48)
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')
    x_position = models.IntegerField(blank=True, null=True)
    y_position = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "p" + str(self.panel.ordinal) + \
        "-" + self.panel.slug + "-hotspot" + "-" + self.title

mural/panels/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from .models import Panel, Article

class PanelListView(ListView):
    model = Panel
    template_name = "index.html"

class AttractListView(ListView):
    model = Panel
    template_name = "attract.html"

class PanelDetailView(DetailView):
    model = Panel
    template_name = "panels/panel_detail.html"

class PanelArticleView(DetailView):
    """
    Two parameters are sent: slug and article_type
    Slug finds the panel. From there we just have to find the right article
    (We're not going directly by article pk, and articles don't have slugs)
    """
    model = Panel
    # context_object_name = 'object'
    template_name = 'panels/article_detail.html'

    # get the initial, intro, article    
    def get_context_data(self, **kwargs):
        # get context
        context = super(PanelArticleView, self).get_context_data(**kwargs)
        # get panel object from detail view
        panel_object = super(PanelArticleView, self).get_object()

        # # for later article_num will come from parameters
        # if kwargs['article_type']:

        #     article_type_arg = self.kwargs['article_type']
        
        article_type_arg = self.kwargs['article_type']


        # else:
        #     article_type_arg = 1

        # if kwargs is not None:
        #     for key, value in kwargs.iteritems():
        #         print ("%s == %s" %(key,value))

        # common_keys = list(dict_a.viewkeys() & dict_b.viewkeys())

        # article_type_arg = 1

        # get the article object
        article = get_object_or_404(Article, panel_id=panel_object.id, 
            article_type=article_type_arg)
        # set the chapter object in the context
        context['article'] = article
        # We need next and previous panel numbers for navigation
        # get_next, get_prev set by properties in Chapter model

        return context

mural/templates/panels/article_detail.html
{% extends "panels/panel_base.html" %}
{% load staticfiles %}

{% block title %}{{ object.panel_title }}{% endblock %}

{% block panel_title %}
    <h3>{{ object.panel_title }}</h3>
    <h1>{{ article.title|safe }}</h1>
    <p class="close-link"><a href="{% url 'panels:panel_detail' object.slug %}">Back</a></p>
{% endblock panel_title %}

{% block panel_content %} {# everything inside the article div #}
<div class="image">
  <img src="{% static 'panels/articlepics/' %}p{{ object.ordinal }}-{{ article.article_type }}.jpg">
  {% if article.article_type == 'intro' %}
    {{ article.caption|safe }}
  {% endif %}
</div>

<!-- begin text article -->
<div class="text-scroll">
  {{ article.narrative|safe }}
</div>

{% if object.visit_set.all %}
  <h3 class="visit-link">Visit Our Exhibit:
  {% for visit in object.visit_set.all %} 
    <a class="pop_item" 
    href="{% url 'pops:visit_ajax_detail' visit.id %}">{{ visit.title|safe}}</a>   
  {% endfor %} 
  </h3>
{% else %}
  <h3 class="visit-link">&nbsp;</h3>
{% endif %}

{# if article.learnmore_set.all #}
<nav class="learn-more">
  <h3>Learn More</h3>
  <ul>
  {% for learnmore in article.learnmore_set.all %}          
    <li>
      <a class="pop_item" href="{% url 'pops:'|add:learnmore.learnmore_type|add:'_ajax_detail' learnmore.id %}">
        <img src="{% static 'pops/learnmore/thumbpics/' %}p{{ learnmore.article.panel.ordinal }}-{{ learnmore.article.article_type }}-{{ learnmore.learnmore_type }}.jpg">
        <span>{{learnmore.get_learnmore_type_display}}:</span>
        {{learnmore.title|safe}}
      </a> 
  </li>
  {% endfor %}    
  </ul>
</nav>
{# endif #}

<!-- end text article -->

{% endblock panel_content %}

mural/templates/panels/panel_base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ object.panel_title }}{% endblock %}

{% block full_page %}

<main class="swipe-main">

  <div class="wrapper">

    <div class="home-nav">
      <a href="/">&larr; Home</a>
    </div>

    <div class="panel-title">     
    {% block panel_title %}
      <h1>{{ object.panel_title }}</h1>

        <p>Child template will fill this in</p>

    {% endblock panel_title %}
    </div>

    <div class="panel-nav"> 
    {% for panel in object.panel_list %}
      {% if panel.ordinal == object.ordinal %}
        <img src="{% static 'images/mini-nav-selected.png' %}">
      {% elif panel.ordinal < 50 %}
        <a href="{% url 'panels:panel_detail' panel.slug %}">
          <img src="{% static 'images/mini-nav.png' %}">
        </a>
      {% endif %}
    {% endfor %}      
    </div>

    <div class="prev-panel">

      {% if object.get_prev %}
        <a class="prev" href="{% url 'panels:panel_detail' object.get_prev.slug %}">
          <img src="{% static 'panels/panelpics/arrow-prev.png' %}">
        </a>        
      {% endif %}

      <svg  xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
        viewBox="0 0 217.2 1800"> <!-- 216 1790 -->

        <image id="document" x="0" y="0" xlink:href="{% static 'panels/panelpics/' %}{{ object.slug }}-prev.jpg" width="217.2" height="1800" />

      </svg>

    </div>

    <div class="main">

  		<article>

        {% block panel_content %}
          panel content here
        {% endblock panel_content %}

  		</article>

      <nav class="tabs">
        <ul>
          {% for nav_article in object.article_set.all %}
            {% if article.article_type == nav_article.article_type %}
              <li class="selected">{{ nav_article.title|safe }}</li>
            {% else %}
              <li><a 
                href="{% url 'panels:article_detail' object.slug nav_article.article_type %}">
                {{ nav_article.title|safe }}</a></li>
            {% endif %}
          {% endfor %}
        </ul>

      </nav>

  	</div><!--/main-->

    <div class="next-panel">

      {% if object.get_next and object.get_next.ordinal < 50 %}
        <a class="next" href="{% url 'panels:panel_detail' object.get_next.slug %}">
          <img src="{% static 'panels/panelpics/arrow-next.png' %}">
        </a>        
      {% endif %}

      <svg  xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
        viewBox="0 0 217.2 1800">

        <image id="document" x="0" y="0" xlink:href="{% static 'panels/panelpics/' %}{{ object.slug }}-next.jpg" width="217.2" height="1800" />

      </svg>
    </div>

  </div><!--/wrapper-->

</main> <!-- swipe-main -->

{% endblock full_page %}

mural/templates/panels/panel_detail.html
{% extends "panels/panel_base.html" %}
{% load staticfiles %}

{% block title %}{{ object.panel_title }}{% endblock %}

{% block panel_title %}
  <h1>{{ object.panel_title }}</h1>
  {{ object.panel_blurb|safe }}
  <!--<p class="more-link"><a href="{% url 'panels:article_detail' object.slug 'intro' %}">learn more...</a></p>-->
{% endblock panel_title %}


{% block panel_content %}

<div class="panel-image">

  <svg  xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
    viewBox="0 0 800 1800">

    <image id="document" x="0" y="0" xlink:href="{% static 'panels/panelpics/' %}{{ object.slug }}.jpg" width="800" height="1800" />

    {% for hotspot in object.hotspot_set.all %}  
      <a class="pop_item" href="{% url 'pops:hotspot_ajax_detail' hotspot.slug %}">
        <circle class="hotspot" cx="{{ hotspot.x_position }}" 
          cy="{{ hotspot.y_position }}" r="72"/>
      </a>
    {% endfor %}    
  </svg>

</div><!--/panel-image-->


{% endblock panel_content %}