mural/pops/urls.py
from django.urls import path

from . import views

app_name="pops"

urlpatterns = [

    path('credits/ajax/<int:pk>/', views.CreditsDetailView.as_view(), 
        name='credits_ajax_detail'),

    path('today/ajax/<int:pk>/', views.TodayDetailView.as_view(), 
        name='today_ajax_detail'),

    path('video/ajax/<int:pk>/', views.VideoDetailView.as_view(), 
        name='video_ajax_detail'),

    path('visit/ajax/<int:pk>/', views.VisitDetailView.as_view(), 
        name='visit_ajax_detail'),

    path('voices/ajax/<int:pk>/', views.VoicesDetailView.as_view(), 
        name='voices_ajax_detail'),

    path('hotspot/ajax/<slug:slug>/', views.HotspotDetailView.as_view(), 
        name='hotspot_ajax_detail'),

    # first call is without slide_num
    path('images/ajax/<int:pk>/', views.ImagesDetailView.as_view(), 
        name='images_ajax_detail'),
    path('images/ajax/<int:pk>/<int:slide_num>/', views.ImagesDetailView.as_view(), 
        name='images_num_ajax_detail'),
    
    path('objects/ajax/<int:pk>/', views.ObjectsDetailView.as_view(), 
        name='objects_ajax_detail'),
    path('objects/ajax/<int:pk>/<int:slide_num>/', views.ObjectsDetailView.as_view(), 
        name='objects_num_ajax_detail'),

]

mural/pops/models.py
from django.db import models

class Learnmore(models.Model):
    """docstring for Learnmore"""
    LEARMORE_TYPE = (
        ('images','Images'),
        ('objects','Objects'),
        ('credits','Credits'),
        ('today','Today'),
        ('video','Video Story'),
        ('voices','Voices'),
    )
    article = models.ForeignKey('panels.Article', on_delete=models.CASCADE)
    learnmore_type = models.CharField(max_length=12, default='today', 
        choices=LEARMORE_TYPE)
    # slug = models.SlugField('short name', max_length=48, unique=True)
    title = models.CharField(max_length=48)
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    def __str__(self):
        return "p" + str(self.article.panel.ordinal) + \
        "-" + self.article.article_type + "-" + self.learnmore_type
        

class Slide(models.Model):
    learnmore = models.ForeignKey('pops.Learnmore', on_delete=models.CASCADE)
    slide_num = models.IntegerField()
    title = models.CharField(max_length=48, blank=True, default='')
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    # next, prev slide, false if none
    def get_next(self):
        next_list = Slide.objects.filter(learnmore_id=self.learnmore_id, 
            slide_num__gt=self.slide_num)
        if next_list:
            return next_list.first()
        return False

    # Special condition added to prevent going back to slide 0 which is the intro
    def get_prev(self):
        prev_list = Slide.objects.filter(learnmore_id=self.learnmore_id, 
            slide_num__lt=self.slide_num).order_by('-slide_num')
        if prev_list:
            prev = prev_list.first()
            if prev.slide_num > 0:
                return prev_list.first()
        return False

    class Meta:
        ordering = ['slide_num']


    def __str__(self):
        return self.learnmore.title + str(self.slide_num)


class Voice(models.Model):
    learnmore = models.ForeignKey('pops.Learnmore', on_delete=models.CASCADE)
    part_num = models.IntegerField('Audio number')
    title = models.CharField(max_length=64, blank=True, default='')
    narrative = models.TextField('Transcription', blank=True, default='')
    # citation = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['part_num']

    def __str__(self):
        return self.learnmore.title + str(self.part_num)

class Visit(models.Model):
    """
    Visit is different from Learnmore because it is a child of Panel, not
    of Article
    """
    panel = models.ForeignKey('panels.Panel', on_delete=models.CASCADE)
    title = models.CharField(max_length=48)
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')

    def __str__(self):
        return "p" + str(self.panel.ordinal) + \
        "-" + self.panel.slug + "-visit"


class Hotspot(models.Model):
    """docstring for Visit"""
    panel = models.ForeignKey('panels.Panel', on_delete=models.CASCADE)
    slug = models.SlugField('short name', max_length=48, unique=True)
    title = models.CharField(max_length=48)
    alt_tag = models.CharField('Image description', max_length=48, blank=True, default='')
    caption = models.TextField(blank=True, default='')
    narrative = models.TextField(blank=True, default='')
    x_position = models.IntegerField(blank=True, null=True)
    y_position = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "p" + str(self.panel.ordinal) + \
        "-" + self.panel.slug + "-hotspot" + "-" + self.title

mural/pops/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from .models import Learnmore, Slide, Hotspot, Visit

# ---- SINGLES ---
class TodayDetailView(DetailView):
    model = Learnmore
    template_name = "pops/today_detail.html"

class VideoDetailView(DetailView):
    model = Learnmore
    template_name = "pops/video_detail.html"

class VoicesDetailView(DetailView):
    model = Learnmore
    template_name = "pops/voices_detail.html"

class CreditsDetailView(DetailView):
    model = Learnmore
    template_name = "pops/credits_detail.html"

class VisitDetailView(DetailView):
    model = Visit
    template_name = "pops/visit_detail.html"

class HotspotDetailView(DetailView):
    model = Hotspot
    template_name = "pops/hotspot_detail.html"

# ---- SLIDE-BASED ---

class SlideDetailView(DetailView):
    """
    To be sub-classed by Images and Objects
    """
    model = Learnmore
    template_name = "pops/images_detail.html"
    # template_name = determined by sub class
    # extend_base - default from MobileFullMixin, or override in sub class
    # link_name and link_class established in  FeatureDetailView  - MobileFullMixin,
    
    # 
    def get_context_data(self, **kwargs):
        context = super(SlideDetailView, self).get_context_data(**kwargs)
        # get the learnmore object
        learnmore_object = super(SlideDetailView, self).get_object()

        # return an error message if no slides have been entered in admin
        if learnmore_object.slide_set.all():
            # use slide_num from param, if it's there
            if 'slide_num' in self.kwargs:
                slide_num_arg = self.kwargs['slide_num']
                # print(" --- slide num in kwargs: " + str(slide_num_arg))
            else: # otherwise, this is zero - the intro
                slide_num_arg = 1
                # print(" --- slide num zeero: " + str(slide_num_arg))

            # get the slide object
            slide = get_object_or_404(Slide, learnmore_id=learnmore_object.id, 
                slide_num=slide_num_arg)
            error_msg = None
        else:
            slide = None
            error_msg = "Error: For learnmore at least one slide has to be " + \
                "defined in Admin."


        # add variables to context
        context.update({'slide': slide, 'error_msg': error_msg})
        # , 'link_name': self.link_name, 'link_class': self.link_class
        return context


class ObjectsDetailView(SlideDetailView):
    model = Learnmore
    template_name = "pops/objects_detail.html"

class ImagesDetailView(SlideDetailView):
    model = Learnmore
    template_name = "pops/images_detail.html"

mural/templates/pops/base_detail.html
{% load staticfiles %}

<div class="slimpop-wrapper">

	<p class="pop-close"><a href="javascript:hideBox();">close</a></p>
		
	<h4 class="subhead">{{ object.get_learnmore_type_display }}</h4>
	<h1>{{ object.title|safe }}</h1>

	{% block slim_content%}
		slim content
	{% endblock slim_content %}

</div><!--slimpop-wrapper -->

mural/templates/pops/base_slide.html
{% extends "pops/base_detail.html" %}
{% load staticfiles %}

{% block slim_content%}

	<div class="pop-img">

		<img src="{% static 'pops/learnmore/fullpics/' %}p{{ slide.learnmore.article.panel.ordinal }}-{{ slide.learnmore.article.article_type }}-{{ slide.learnmore.learnmore_type }}-{{ slide.slide_num }}.jpg">
		{{ slide.caption|safe }}

	</div> 

	<h4>{{ slide.title|safe }}</h4>
	{{ slide.narrative|safe }}

	<nav class="slide-nav">
		<ul>

			<li>
		    {% if slide.get_prev %}
		      <a class="swap_pop" id="swap_prev" name="{{slide.learnmore.learnmore_type}}/{{slide.learnmore.id}}" 
		      href="{% url 'pops:'|add:slide.learnmore.learnmore_type|add:'_num_ajax_detail' slide.learnmore.id slide.get_prev.slide_num %}">&larr; Previous</a>
		    {% else %}
		      <span class="no-more">&larr;  previous</span>
		    {% endif %}

		  |
		  
		    {% if slide.get_next %}
		      <a class="swap_pop" id="swap_next" name="{{slide.learnmore.learnmore_type}}/{{slide.learnmore.id}}" 
		      href="{% url 'pops:'|add:slide.learnmore.learnmore_type|add:'_num_ajax_detail' slide.learnmore.id slide.get_next.slide_num %}">Next &rarr;</a>
		    {% else %}
		      <span class="no-more">next &rarr;</span>
		    {% endif %}
			</li>

		</ul>
	</nav>

{% endblock slim_content %}

mural/templates/pops/credits_detail.html
{% load staticfiles %}
{# Avoids extending pop/base_detail.html so that we don't show the h4 subhead for credits #}

<div class="slimpop-wrapper">
	<p class="pop-close"><a href="javascript:hideBox();">close</a></p>
		
	<h1>{{ object.title|safe }}</h1>

	{{ object.narrative|safe }}

</div><!--slimpop-wrapper -->

mural/templates/pops/hotspot_detail.html
{% extends "pops/base_detail.html" %}
{% load staticfiles %}

{% block slim_content%}
		
	<div class="pop-img">

		<img src="{% static 'pops/hotspot/' %}p{{ object.panel.ordinal }}-{{ object.slug }}.jpg">
		{{ object.caption|safe }}

	</div> 

	{{ object.narrative|safe }}
    
{% endblock slim_content %}

mural/templates/pops/images_detail.html
{% extends "pops/base_slide.html" %}
{% load staticfiles %}

{# so far images and objects offer no exceptions to the shared base_slide.html #}

mural/templates/pops/objects_detail.html
{% extends "pops/base_slide.html" %}
{% load staticfiles %}

{# so far images and objects offer no exceptions to the shared base_slide.html #}

mural/templates/pops/today_detail.html
{% extends "pops/base_detail.html" %}
{% load staticfiles %}

{% block slim_content%}
		
	<div class="pop-img">

		<img src="{% static 'pops/learnmore/fullpics/' %}p{{ object.article.panel.ordinal }}-{{ object.article.article_type }}-{{ object.learnmore_type }}.jpg">
		{{ object.caption|safe }}

	</div> 

	{{ object.narrative|safe }}
    
{% endblock slim_content %}

mural/templates/pops/video_detail.html
{% extends "pops/base_detail.html" %}
{% load staticfiles %}

{% block slim_content%}
		
	<div id="video-content">

		<video  width="720" height="405" controls="controls" poster="{% static 'pops/learnmore/media/' %}p{{ object.article.panel.ordinal }}-{{ object.article.article_type }}-{{ object.learnmore_type }}.jpg">
			<source src="{% static 'pops/learnmore/media/' %}p{{ object.article.panel.ordinal }}-{{ object.article.article_type }}-{{ object.learnmore_type }}.webm" type="video/webm">
			<source src="{% static 'pops/learnmore/media/' %}p{{ object.article.panel.ordinal }}-{{ object.article.article_type }}-{{ object.learnmore_type }}.mp4" type="video/mp4">
			Your browser does not support the video tag.
		</video>

		{{ object.caption|safe }}

	</div> 

	{{ object.narrative|safe }}
    
{% endblock slim_content %}

mural/templates/pops/visit_detail.html
{% extends "pops/base_detail.html" %}
{% load staticfiles %}

{% block slim_content%}
		
	<div class="pop-img">

		<img src="{% static 'pops/learnmore/fullpics/' %}p{{ object.panel.ordinal }}-visit.jpg" alt="{{ object.alt_tag }}">
		{{ object.caption|safe }}

	</div> 

	{{ object.narrative|safe }}
    
{% endblock slim_content %}

mural/templates/pops/voices_detail.html
{% extends "pops/base_detail.html" %}
{% load staticfiles %}

{% block slim_content%}
		
  {{ learnmore.narrative|safe }}

  {% for voice in learnmore.voice_set.all %}          


  <h3>{{ voice.title|safe}} </h3>
  <audio class="voices" controls="">
    <source src="{% static 'pops/learnmore/media/' %}p{{ voice.learnmore.article.panel.ordinal }}-{{ voice.learnmore.article.article_type }}-{{ voice.learnmore.learnmore_type }}-{{ voice.part_num }}.m4a" type="audio/mpeg">
    <source src="{% static 'pops/learnmore/media/' %}p{{ voice.learnmore.article.panel.ordinal }}-{{ voice.learnmore.article.article_type }}-{{ voice.learnmore.learnmore_type }}-{{ voice.part_num }}.mp3" type="audio/mp3">
    <source src="{% static 'pops/learnmore/media/' %}p{{ voice.learnmore.article.panel.ordinal }}-{{ voice.learnmore.article.article_type }}-{{ voice.learnmore.learnmore_type }}-{{ voice.part_num }}.oggXX" type="audio/ogg">
    <!-- fallback -->
       Your browser does not support the HTML5 audio element; instead you can 
       <a href="pops/media/spago-quote.mp3">download 
        this MP3 audio file.</a>
  </audio>

  <blockquote><!-- transcription -->
	{{ voice.narrative|safe }}      
  <cite>(citation - in transcription,or separate?)</cite> 


  </blockquote>

  {% endfor %}

{% endblock slim_content %}